name: "Export"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  export:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Impacto
          path: dist
